### ISSUE TITLE
Setup guidelines/restrictions on what languages will be used

### ISSUE THREAD

**Issue by CrimsonCodes0** [whippingdot/Language-Tutorials#10]
Currently, a tutorial can be made for any language, provided that it's name does not contain a "curse word."

This opens up the doors to a lot more than anyone would ever care to read about.

For example, if I create a language without an implementation *right now*, and no one knows about it, nor uses it, can a tutorial about it be made here?

If you say, "no," then there obviously have to be some entry barrier restrictions, guiding us to not allow all sorts of nonsense.

I've opened this issue to encourage discussion on the topic, and development of those restrictions, if any.

**Comment by Rayyan06** [comment]
I think a guidelines.md file should be added in the root, or maybe a list of guidelines added to the README.md. In the future we might decide on something.

**Comment by cursorweb** [comment]
Well, what should happen is that the main branch is protected. This way, we can only contribute with prs, and using code review, no obscure tutorials would be allowed.

**Comment by cursorweb** [comment]
@whippingdot what u think

**Comment by whippingdot** [comment]
> @whippingdot what u think

ur absolutely right, you can only contribute from prs mainly (i don't know what code review is). The thing is, I gotta delete that line that says you can create tutorials of anything that doesn't have a bad word in its name. It would make sense to NOT have that. 😄 @CrimsonCodes0 thanks for adding this issue anyway...

**Comment by whippingdot** [comment]
Can I close this?

**Comment by CrimsonCodes0** [comment]
@whippingdot It's your project, of course you can close it.

**Comment by whippingdot** [comment]
> @whippingdot It's your project, of course you can close it.

no I was asking if u had anything else to say.

**Comment by CrimsonCodes0** [comment]
Ah, well, an implementation of the suggestion might've been nice.

Also, code review is merely the action of reviewing the changed code from a PR.

**Comment by cursorweb** [comment]
dw if you give admin i'll set it up for you

then you can revoke

**Comment by whippingdot** [comment]
?? set what up for me.
