### ISSUE TITLE
C++ Tutorial tweaks

### ISSUE THREAD

**Issue by CrimsonCodes0** [whippingdot/Language-Tutorials#11]
There's a good amount of the C++ tutorial that coud be improved as to not alientate readers right off the bat.

For example, Advanced-Operators.md shows `std::cout` logging `0` and `1` for booleans.

[In my fork](https://github.com/CrimsonCodes0/Language-Tutorials/blob/main/C%2B%2B/4.%20Advanced-Operators.md), I added `std::boolalpha` so the code would show `true` or `false`, which are much more "human-friendly," especially helpful if you're learning the language (which is the audience that tutorials tend to target).

Also, the entire file seems like a misnomer, as the operatiors aren't that "advanced," especially considering how there is a whole plethora of C++ operators that hadn't been covered yet.

Besides that, there's plenty of small errors, such as calling `cout` and `cin` keywords in Setup.md, instead of globals, or multi-level comments instead of multi-line comments.

**Comment by whippingdot** [comment]
Umm can you create a pr with all your changes. I am sorry I made all of these. At first I thought that it outputs `True` or `False` in the console but when I tried the program out it didn't. I like your boolalpha thing - but you have to explain what that does after the code block. Please do so. Also fix the other things like the `cout` and `cin` as I didn't understand what you were saying

**Comment by whippingdot** [comment]
Also I meant advanced cause beginners don't really need to learn all these when they first learn about operators.

**Comment by CrimsonCodes0** [comment]
Sure, I'll make the adjustments in a PR in roughly 14-16 hours.

As for cout, cin, they are merely global variables, not keywords.

Keywords are, for lack of a better word, permeant, that is, they cannot be imported from a file, that fundamentally makes no sense.

```c++
namespace std {
    std::ostream cout = ...;
    std::istream cin = ...;
}
```
No "magic" whatsoever, they're implemented in plain C++.
