### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by darkdarcool** [whippingdot/Language-Tutorials#23]
Hai! So I have been working on a draft(or final product if I don't wanna improve my trash parser) for my new Markdown thing called DSMD(DarkScript Markdown). I was going to make a tutorial over on the repo over there, but then I thought this was a good excuse to put a tutorial here, and leave a link to it over on my repo. 

You can think it over, the link to the repository is here:
https://github.com/darkdarcool/DSMD-Compiler

And if you decline, I'll just put the tutorial over on my repo

THX!!!(bai)

**Comment by darkdarcool** [comment]
###### And if I put the md here, it would be in actual md, not DSMD, because that wouldn't be possible.

**Comment by whippingdot** [comment]
What is DSMD supposed to do? Is it a coding language?

**Comment by darkdarcool** [comment]
@whippingdot, no, sorta like a markdown lang. It compiles to markdown like typescript to js. So you code a DSMD file. Then the interpreter compiles and spits out an md file with the markdown translation of your DSMD file.

**Comment by whippingdot** [comment]
UR choice if you want to make a tutorial

**Comment by darkdarcool** [comment]
okiiiiiiie. I'll probs put it here then as this repo is meant a little bit more for tutorials
