### ISSUE TITLE
DSMD Completion for V0.1

### ISSUE THREAD

**Issue by whippingdot** [whippingdot/Language-Tutorials#27]
@darkdarcool I wanna ship V0.1 and I am pretty sure the only thing I am waiting on is DSMD. Can you please finish DSMD, and if you are not going to can you tell me?

**Comment by darkdarcool** [comment]
I can work on it Saturday and Sunday.

**Comment by whippingdot** [comment]
Kk, please do so

**Comment by darkdarcool** [comment]
Fixed in a34759c

**Comment by whippingdot** [comment]
You are not gonna add any more dsmd? Can I just delete the folder altogether?

**Comment by darkdarcool** [comment]
> You are not gonna add any more dsmd? Can I just delete the folder altogether?

I pretty much covered the whole thing. But if you want to delete it you can

**Comment by whippingdot** [comment]
Oh okay you covered it all? Then it's fine
